[unix_http_server]
file=/tmp/supervisor.sock
chmod=0770
chown=root:ubuntu

[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
user=root

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = /etc/supervisor/conf.d/supervisor-brain-api.conf
